"""qa-store — the shared MongoDB store for the Persona QA Agents epic (#616).

Owns the ``slyreply_qa`` database: collections (``qa_runs``,
``qa_findings``, ``qa_run_steps``, ``qa_run_logs``, ``qa_scenarios``,
``qa_personas``, ``qa_discovered_*``) plus a GridFS bucket
(``qa_screenshots``) for Playwright capture bytes (#860). pymongo only —
kept deliberately light so the review UI API does not have to pull the
Claude Agent SDK in just to read findings.

Also houses the **coverage catalog** (#859, #861) — a static enumeration
of every user-facing action SlyReply supports. Lives here, not in the
``qa_agents`` harness package, because the review UI's API server reads
it to render the trigger-page mandatory-actions checklist; importing it
from the harness would drag the entire Claude Agent SDK into the review
UI image. Pure data + a dataclass — no qa-store-specific deps either.
"""

from __future__ import annotations

from .coverage_catalog import (
    CATALOG,
    CATEGORIES,
    KNOWN_PERSONA_IDS,
    CoverageAction,
)
from .distillation import (
    DISTILLATION_MODEL,
    distill_persona_run,
)
from .distillation import (
    is_enabled as is_distillation_enabled,
)
from .fixtures import (
    DEFAULT_FIXTURES,
    REQUIRED_CATALOG_KEYS,
    FixtureCatalogError,
    flat_placeholders,
    load_fixture_catalog,
    load_fixtures,
)
from .schema import (
    DISCOVERED_ACTION_CATEGORIES,
    FINDING_STATUSES,
    PERSONA_COLOR_TOKENS,
    RUN_LOG_KINDS,
    RUN_LOG_TTL_SECONDS,
    RUN_STATUSES,
    add_persona_result,
    all_personas_reviewed,
    append_run_log,
    apply_cross_run_dedup_for_run,
    attach_finding_to_step,
    attach_screenshot_to_step,
    bump_finding_recurring,
    claim_run_finish,
    clear_discovered_for_persona_run,
    clear_persona_credentials,
    connect,
    create_persona,
    create_run,
    create_scenario,
    delete_persona,
    delete_scenario,
    find_prior_finding,
    finish_run,
    get_finding,
    get_persona,
    get_persona_credentials,
    get_persona_credentials_status,
    get_persona_resume_token,
    get_run,
    get_scenario,
    list_admin_wipes,
    list_discovered_actions,
    list_discovered_branches,
    list_discovered_tools,
    list_personas,
    list_run_logs_for_persona,
    list_runs,
    list_scenarios,
    list_steps_for_persona,
    mark_finding_filed,
    mark_run_filed,
    normalised_title_hash,
    record_admin_wipe,
    record_persona_resume_token,
    record_persona_session,
    record_step,
    search_run_logs,
    set_finding_status,
    set_persona_credentials,
    summarise_mcp_servers_used,
    toggle_persona_active,
    update_finding_gh_state,
    update_persona,
    update_scenario,
    upsert_discovered_action,
    upsert_discovered_branch,
    upsert_discovered_tool,
    upsert_live_finding,
    upsert_persona,
)
from .screenshots import (
    delete_screenshot,
    fetch_screenshot,
    store_screenshot,
)
from .seed_personas import reset_default_personas, seed_default_personas
from .wipe import list_drop_targets, wipe_for_relaunch

__all__ = [
    "CATALOG",
    "CATEGORIES",
    "CoverageAction",
    "DISCOVERED_ACTION_CATEGORIES",
    "FINDING_STATUSES",
    "KNOWN_PERSONA_IDS",
    "PERSONA_COLOR_TOKENS",
    "RUN_LOG_KINDS",
    "RUN_LOG_TTL_SECONDS",
    "RUN_STATUSES",
    "REQUIRED_CATALOG_KEYS",
    "FixtureCatalogError",
    "load_fixture_catalog",
    "add_persona_result",
    "all_personas_reviewed",
    "append_run_log",
    "apply_cross_run_dedup_for_run",
    "attach_finding_to_step",
    "attach_screenshot_to_step",
    "bump_finding_recurring",
    "claim_run_finish",
    "clear_discovered_for_persona_run",
    "connect",
    "create_persona",
    "create_run",
    "create_scenario",
    "delete_persona",
    "delete_scenario",
    "delete_screenshot",
    "fetch_screenshot",
    "find_prior_finding",
    "finish_run",
    "get_finding",
    "get_persona",
    "get_run",
    "get_scenario",
    "list_admin_wipes",
    "list_discovered_actions",
    "list_discovered_branches",
    "list_discovered_tools",
    "list_personas",
    "list_run_logs_for_persona",
    "list_runs",
    "list_scenarios",
    "list_steps_for_persona",
    "mark_finding_filed",
    "mark_run_filed",
    "normalised_title_hash",
    "clear_persona_credentials",
    "get_persona_credentials",
    "get_persona_credentials_status",
    "get_persona_resume_token",
    "record_admin_wipe",
    "record_persona_resume_token",
    "record_persona_session",
    "record_step",
    "search_run_logs",
    "set_finding_status",
    "set_persona_credentials",
    "summarise_mcp_servers_used",
    "store_screenshot",
    "update_finding_gh_state",
    "toggle_persona_active",
    "update_persona",
    "upsert_discovered_action",
    "upsert_discovered_branch",
    "upsert_discovered_tool",
    "update_scenario",
    "upsert_live_finding",
    "upsert_persona",
    "reset_default_personas",
    "seed_default_personas",
    "DISTILLATION_MODEL",
    "distill_persona_run",
    "is_distillation_enabled",
    "wipe_for_relaunch",
    "list_drop_targets",
    "DEFAULT_FIXTURES",
    "flat_placeholders",
    "load_fixtures",
]
